### ISSUE TITLE
Bootstrap stars in welcome message

### ISSUE THREAD

**Issue by laszlokorte** [henryboldi/felony#10]
Not sure if it's on purpose but after generating my key it get prompted to star twbs/bootstrap on Guthub. I guess it should be linked to henryboldi/felony instead?

![bildschirmfoto 2016-07-04 um 15 12 35](https://cloud.githubusercontent.com/assets/26493/16561502/df406908-41f9-11e6-97ea-a7bfa478c18b.png)

**Comment by MichalPaszkiewicz** [comment]
I have created a pull request for this

#18
