### ISSUE TITLE
Is Felony still being maintained?

### ISSUE THREAD

**Issue by vstath** [henryboldi/felony#109]
I am wondering whether this project is still maintained. 

Last release was more than a year ago and there are problems installing on windows for some time now.

**Comment by daveloyall** [comment]
Yes.  [New commits](https://github.com/henryboldi/felony/commits/master) are still coming in all the time.  That list only shows commits in the `master` branch.

Issues #14, #30, #32, and #96 are all about failures when installing on Windows.  The developer has asked for some help with this.

That's all I know.

**Comment by henryboldi** [comment]
Yes! I'll get a new release built here soon.
