### ISSUE TITLE
Verify message: `undefined`

### ISSUE THREAD

**Issue by laszlokorte** [henryboldi/felony#11]
If a verify a signed message from someone who is not in my contact list I get "undefined" as match.

I think it should rather say something like: "The author of this message seems to be not in your contact list"

![bildschirmfoto 2016-07-04 um 15 15 26](https://cloud.githubusercontent.com/assets/26493/16561659/a2177e58-41fa-11e6-92f6-d6165bd9f508.png)

**Comment by kiliankoe** [comment]
Same comes up if I verify a message from myself. Presumably as I am also not in my contact list?

**Comment by laszlokorte** [comment]
@kiliankoe yes if you add yourself to your own contact list it will work.

**Comment by frankcash** [comment]
Great suggestions, and thanks for reporting this issue!

![screen shot 2016-08-16 at 9 21 29 pm](https://cloud.githubusercontent.com/assets/6012231/17721342/7b12328e-63f7-11e6-803d-aa7496203c29.png)
