### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by DanielRuf** [henryboldi/felony#114]
We could need some new releases and tags:

https://github.com/henryboldi/felony/compare/0.10.3...master

**Comment by Fastidious** [comment]
I have the feeling this is abandonware, @DanielRuf.

**Comment by henryboldi** [comment]
If you'd like to make a new release @Fastidious, please go right ahead. I'd be glad to accept the pull request.

**Comment by Fastidious** [comment]
@henryboldi if I could, I would, but I am not a programmer, and thus lack of all the skills required 😬.

**Comment by frankcash** [comment]
@DanielRuf are you looking for new features or a release from master?

**Comment by DanielRuf** [comment]
@frankcash well, there are a *few* changes, see https://github.com/henryboldi/felony/compare/0.10.3...master
