### ISSUE TITLE
URL felony.io isn't working

### ISSUE THREAD

**Issue by lfacchinelli** [henryboldi/felony#15]
Hi !

I copied my public key (created by felony and copied through the GUI) and when I pasted it says something like "Comment: 👀 How dafuq do I use this? --> http://felony.io 😉" 

Well, that website is not working, only shows a 404.

**Comment by henryboldi** [comment]
The site is in 'gh-pages', but in the meantime i'll have it redirect to the Github repo

**Comment by lfacchinelli** [comment]
Yes, that's a good idea !

**Comment by henryboldi** [comment]
Fixed! Thanks 💓

**Comment by lfacchinelli** [comment]
Thanks to you! awesome project btw !
