### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by achekroud** [henryboldi/felony#19]
Hi team

I'm new to this area (and also new to node). I saw the post on hackernews and wanted to give this a try. 

I tried to follow the instructions to get started and had a few hiccups. Here was my error message. I'm sure there is a simple fix here, but if I had this issue I'm sure other tourists will also.
[npm-debug copy.txt](https://github.com/henryboldi/felony/files/346407/npm-debug.copy.txt)

adamchekroud $ npm run package

> felony@0.10.2 package /Users/adamchekroud/felony
> cross-env NODE_ENV=production node -r babel-register package.js

```
sh: cross-env: command not found

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "run" "package"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! felony@0.10.2 package: `cross-env NODE_ENV=production node -r babel-register package.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the felony@0.10.2 package script 'cross-env NODE_ENV=production node -r babel-register package.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the felony package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node -r babel-register package.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs felony
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls felony
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adamchekroud/felony/npm-debug.log

```

I also attached the npm-debug.log but as a .txt since github didn't like the .log file format.

**Comment by ameesme** [comment]
Hi @achekroud.
It looks like you are missing some npm dependencies. Try running `npm install`, then retry.

**Comment by achekroud** [comment]
@ameesme nailed it -- thanks a lot for your help!

**Comment by ameesme** [comment]
Np! Let me know if I can help you with anything else:).
