### ISSUE TITLE
not working on ubuntu

### ISSUE THREAD

**Issue by oren** [henryboldi/felony#20]
I see empty window. with 'file', 'view', and 'help'. file -> open does nothing and no error in the terminal.

**Comment by BoringCode** [comment]
Seems to be related to an error that Electron is throwing on launch.

```
ELECTRON_ASAR.js:158 Uncaught Error: Module version mismatch. Expected 47, got 48.
module.(anonymous function) @ ELECTRON_ASAR.js:158
Module._extensions..node @ module.js:440
module.(anonymous function) @ ELECTRON_ASAR.js:158
Module.load @ module.js:357Module._load @ module.js:314
Module.require @ module.js:367
require @ internal/module.js:16
(anonymous function) @ node_modules/keytar/lib/keytar.js:4
(anonymous function) @ node_modules/keytar/lib/keytar.js:58
Module._compile @ module.js:413
Module._extensions..js @ module.js:422
Module.load @ module.js:357Module._load @ module.js:314
Module.require @ module.js:367
require @ internal/module.js:16
(anonymous function) @ external "keytar"?c4e9:1
(anonymous function) @ bundle.js:950
__webpack_require__ @ bundle.js:557
fn @ bundle.js:88
(anonymous function) @ pgp.js?b688:6
(anonymous function) @ bundle.js:944
__webpack_require__ @ bundle.js:557
fn @ bundle.js:88
(anonymous function) @ Alias.js?5486:8
(anonymous function) @ bundle.js:896
__webpack_require__ @ bundle.js:557
fn @ bundle.js:88
(anonymous function) @ Header.js?fa34:9
(anonymous function) @ bundle.js:884
__webpack_require__ @ bundle.js:557
fn @ bundle.js:88
(anonymous function) @ HeaderContainer.js?e915:3
(anonymous function) @ bundle.js:824
__webpack_require__ @ bundle.js:557
fn @ bundle.js:88
(anonymous function) @ Felony.js?48cf:12
(anonymous function) @ bundle.js:722
__webpack_require__ @ bundle.js:557
fn @ bundle.js:88
(anonymous function) @ index.js?2018:9
(anonymous function) @ bundle.js:650
__webpack_require__ @ bundle.js:557
fn @ bundle.js:88
(anonymous function) @ bundle.js:589
__webpack_require__ @ bundle.js:557
(anonymous function) @ bundle.js:580
(anonymous function) @ bundle.js:583
```

**Comment by socketubs** [comment]
Same error here.

**Comment by robmyers** [comment]
Same empty window on Debian Jessie.

**Comment by melvincarvalho** [comment]
Same,  no error message.  I also get error related to keytar when buidling.

Close window works.  As does full screen, and f11 (I guessed) to toggle.

**Comment by MingweiSamuel** [comment]
I am getting the same error, but without the trace:
![felony](https://cloud.githubusercontent.com/assets/6778341/16570915/489427a4-4205-11e6-94bc-1067db274848.png)

**Comment by brbsix** [comment]
For anyone interested, I was able to get this fixed. You can download it here: https://github.com/brbsix/felony/releases/download/0.10.3/Felony-linux-0.10.3-x64.zip

I have no experience with the framework (I just wanted to test-drive the app) so I'm not certain where the issue is. Essentially I just took care of the warning messages (renaming the deprecated title-bar-style and removing the crash reporter per the recommendation of the boilerplate app), updated to a more recent version of electron-prebuilt, then used Node v6.3.0 to build and package it.

**Comment by greg-js** [comment]
I can confirm the development version runs (albeit with errors which may or may not be related to this workaround) after updating `electron-prebuilt` to the latest version (1.2.6 at the time of writing) and removing the crash reporter from `main.development.js`. FWIW I'm on Node 6.2.1 and Arch Linux.

**Comment by frankcash** [comment]
This should be updated, please let me know. I'll re-open then!

**Comment by xssc** [comment]
@frankcash I'm still getting this issue on ubuntu 14.0.4

**Comment by TechyPeople** [comment]
You're probably running a packaged pre-release -- 0.10.3 does not have the fix. It's easy to package the latest source yourself, though: download/clone the repo, install dependencies, and `npm run package`.

On Sat, Aug 13, 2016 at 5:33 PM, Sawyer Charles < notifications@github.com [notifications@github.com] > wrote:
@frankcash [https://github.com/frankcash] I'm still getting this issue on ubuntu 14.0.4

**Comment by xssc** [comment]
Thanks that worked

**Comment by frankcash** [comment]
💯
