### ISSUE TITLE
Please change the name

### ISSUE THREAD

**Issue by ascendantlogic** [henryboldi/felony#22]
Creating an app for the "average person" and calling it felony does not do the greater cryptographic community any favors in the PR battle we have with the NSA, FBI et al that argue encryption allows for illegality.

**Comment by chris-kahn** [comment]
Thought what someone wrote on HN was appropriate:

    A new app called Felony allows ISIS and online pedophiles to communicate in secret with ease.

**Comment by josiahsprague** [comment]
Hmm @henryboldi just closed this serious issue without even so much as a comment. That doesn't communicate that this is a project that really cares about promoting the use of encryption.

**Comment by omouse** [comment]
This is the worst fucking name in the world and it's a *gift* to every single dictator, authoritarian and anti-privacy anti-liberty advocate out there. Please change the name to something that won't drive potential users away.

**Comment by chris-kahn** [comment]
Ok guys, let's put down the pitchforks, I think he got the message.

**Comment by josephdviviano** [comment]
+1 for changing this name, this is bad marketing (though I personally think it's pretty funny). I think a good deal of potential users will be turned off of using this for fear of oppression etc.

**Comment by jbenet** [comment]
@henryboldi 
- Change the name. It's all fun and games, until brute governments with zero patience arrest someone, and politically charged headlines make the legitimate use of encryption harder.
- This is plainly irresponsible, and unwelcome in the broader cryptography and infosec communities.
- Closing the issue without even discussing sets a pretty negative collaboration tone, too. You have great momentum in just one day, don't squander it by alienating possible supporters and contributors.
- You have a well thought out, well designed application here. Don't throw that away for the sake of a joke.
- As menzoic on HN suggested, what about "Freedom"? It sends the right message.
