### ISSUE TITLE
Requires "concurrently"

### ISSUE THREAD

**Issue by Garbaz** [henryboldi/felony#24]
When running any of the `npm run [...]` commands on my Debian machine, I get an error message from npm, telling me that it fails at
`concurrently --kill-others "npm run hot-server" "npm run start-hot"`
and my shell tells me
> sh: 1: concurrently: not found

It seems to as if this is an apple shell command not present on Linux. If possible, a universal Posix command should be used.

I have to add that I have no experience whatsoever with `npm`, so this might be my fault.

**Comment by josephdviviano** [comment]
Try this: `npm install -g concurrently`

more here: https://github.com/RickWong/react-isomorphic-starterkit/issues/12

**Comment by hanford** [comment]
@josephdviviano @Garbaz 

I think there is a super simple solution here. To be able to run concurrently directly from the CLI requires the dependency to be installed globally, however if you were to add 

```json 
"scripts": {
 "concurrently": "concurrently"
}
```

to the `package.json` and run `npm run concurrently` .. I believe the dependency no longer needs to be installed globally. At least that trick works with webpack.

**Comment by Garbaz** [comment]
@josephdviviano @hanford 
Thanks, both ways solve the problem (For this dependency and others).
