### ISSUE TITLE
Add to brew cask 

### ISSUE THREAD

**Issue by AndrewSB** [henryboldi/felony#29]
http://caskroom.io

**Comment by ariporad** [comment]
+1, this would be really awesome!

**Comment by brettneese** [comment]
Working on this right now. Shouldn't be too long.

**Comment by brettneese** [comment]
Boom. (Not sure if this gets automerged or if the Hombrew Cask folks have to merge it manually, but should be set either way soon enough.)

https://github.com/caskroom/homebrew-cask/pull/22613

**Comment by henryboldi** [comment]
Thanks @brettneese! 💓

**Comment by brettneese** [comment]
💓
