### ISSUE TITLE
0.10.3 Linux visual issue

### ISSUE THREAD

**Issue by ajay340** [henryboldi/felony#33]
I'm on debian jessie.

I downloaded the 64 zip and extracted it. When I clicked on felony it showed this. Please help 

![screenshot at 2016-07-04 22-19-43](https://cloud.githubusercontent.com/assets/10181135/16572350/b1568180-4235-11e6-8341-0f9f64f55a43.png)

**Comment by jalcine** [comment]
Can confirm this issue on Kubuntu 16.04 as well.

**Comment by primis** [comment]
Can confirm on Fedora 24 as well

**Comment by Spirou4D** [comment]
Confirm the same issue on Linux Mint Rosa 17.3 64Bytes

**Comment by fillup** [comment]
I have same problem on Ubuntu 16.04

**Comment by ajay340** [comment]
When will this get fixed?

**Comment by josephdviviano** [comment]
+1

**Comment by brbsix** [comment]
I've uploaded a fix at https://github.com/brbsix/felony/releases/latest. For more info, see https://github.com/henryboldi/felony/issues/20#issuecomment-231040673.

**Comment by ajay340** [comment]
Just downloaded the "fixed" version and nothing was fixed. I still get the same blank screen.

**Comment by manoharprabhu** [comment]
Getting an empty panel with developer tools even with the 1.2.6 electron-prebuilt.
I run Fedora 23.
![felony_fedora](https://cloud.githubusercontent.com/assets/2051859/16713393/b2aaed7c-46c3-11e6-8fc6-9f0cd79d249f.png)

**Comment by brbsix** [comment]
@manoharprabhu Can you try with the release I uploaded at https://github.com/brbsix/felony/releases/download/0.10.3-fixed/Felony-linux-x64.zip and confirm the issue still exists? I noticed running `npm run dev` was inconsistent at times.

**Comment by manoharprabhu** [comment]
The uploaded release seems to work fine.

**Comment by frankcash** [comment]
Let me know if this problem still persists, closing until then.
