### ISSUE TITLE
How run Felony?

### ISSUE THREAD

**Issue by Spirou4D** [henryboldi/felony#36]
Hi Mr the coder,

I have downloaded the bin release of Felony for Linux 64bytes and clic on the Felony file to run the application.
I have this : http://storage4.static.itmages.com/i/16/0705/h_1467709267_6347825_8624d0bc8f.jpeg
And after that if I make open: nothing?
Is he on the good path, please?

**Comment by Spirou4D** [comment]
I have run Felony in Terminal. Here is the traceback:
patrinux@patrinux-ordi ~/Applications/Felony $ ./Felony
(electron) companyName is now a required option to crashReporter.start
(electron) title-bar-style is deprecated. Use titleBarStyle instead.

and then the same white windows as before!

**Comment by zamber** [comment]
Same here on `4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`.

**Comment by brbsix** [comment]
I've uploaded a fix at https://github.com/brbsix/felony/releases/latest. For more info, see https://github.com/henryboldi/felony/issues/20#issuecomment-231040673.

**Comment by Spirou4D** [comment]
With the last correction, Felony run very well on my Linux 64Bytes Rosa 17.3!
_A great thanks_ for Henry Boldi alias **brbsix**!

**Comment by frankcash** [comment]
Let me know if you still have this problem after the latest update.
