### ISSUE TITLE
electron warnings on launch

### ISSUE THREAD

**Issue by primis** [henryboldi/felony#42]
(electron) companyName is now a required option to crashReporter.start
(electron) title-bar-style is deprecated. Use titleBarStyle instead.

---
EDIT:
This was on Fedora24

**Comment by josephdviviano** [comment]
+1

**Comment by burdzz** [comment]
+1 OS: Debian GNU/Linux 8.5 (jessie) 8.5.

**Comment by henryboldi** [comment]
Closing as this is a duplicate
