### ISSUE TITLE
OS X: No way to re-open window when it's been closed

### ISSUE THREAD

**Issue by danielhoherd** [henryboldi/felony#45]
After closing the Felony window, there is no way to re-open the window without closing and re-launching the app.

**Comment by henryboldi** [comment]
Good catch

**Comment by jarrydfillmore** [comment]
+1!

**Comment by tobycyanide** [comment]
Looking at this right now!

**Comment by tobycyanide** [comment]
#61

**Comment by TechyPeople** [comment]
#61 was merged a while ago, fixing this issue.  closing for that reason, thanks @tobycyanide 😄
