### ISSUE TITLE
Data Validation&Unable to copy on El Capitan

### ISSUE THREAD

**Issue by viralis** [henryboldi/felony#47]
Sorry about the confusing. I revised the writing below. Originally, I thought the two problems might be operated, but I think they are actually related.

When the first time I launched the app, I need to fill-in some information such as name, email, etc to generate the key. However, in this screen, I can skip all the fields and click the "Generate Key" button without any warning. Still, after I clicked the button, I will receive a notification says something like "the key has been generated".

The problem of unable to copying public key might be because there is no key has been generated, since all other functions in the app(sign, etc.) is not working, too.

**Comment by henryboldi** [comment]
I am confused. What's broken?

**Comment by TechyPeople** [comment]
fixed in #58, which was merged.
