### ISSUE TITLE
Error when starting Felony on Windows 7 (64-bit)

### ISSUE THREAD

**Issue by pherelad** [henryboldi/felony#49]
When I double click on the executable in Windows 7 64-bit, I am greeted with the following error message:

<img width="576" alt="error" src="https://cloud.githubusercontent.com/assets/14049109/16657238/5e77a716-4427-11e6-99c5-9cc765fa4abb.png">

**Comment by henryboldi** [comment]
Thanks for the report. Currently, it doesn't seem like Felony is working for Windows.

**Comment by cdokolas** [comment]
Duplicate of #14

**Comment by pherelad** [comment]
Gotcha, thanks for the FYI!

**Comment by frankcash** [comment]
Closing since duplicate.  Thanks for reporting though!
