### ISSUE TITLE
PR: Migration to spectron?

### ISSUE THREAD

**Issue by amilajack** [henryboldi/felony#51]
Willing to make a PR to add [spectron](electron.atom.io/spectron) tests. Just checking if this PR would be welcome before I make it. Thanks!

**Comment by henryboldi** [comment]
This PR would be super welcome! PR away 💓

**Comment by amilajack** [comment]
Actually before I do this, can you enable travis ci tests. That would make PR's easier.

**Comment by amilajack** [comment]
I've made a PR to add the tests:

https://github.com/henryboldi/felony/pull/50
