### ISSUE TITLE
No way to close/dismiss after decrypting, only "Copy & Close"

### ISSUE THREAD

**Issue by vdh** [henryboldi/felony#68]
It's quite awkward to be left stuck unable to dismiss the decryption window without needlessly modifying the clipboard.

![screen shot 2016-07-18 at 10 42 32 am](https://cloud.githubusercontent.com/assets/573501/16904176/6adc0c94-4cd4-11e6-8480-9ac381d3b53e.png)

**Comment by frankcash** [comment]
![screen shot 2016-08-06 at 6 32 40 pm](https://cloud.githubusercontent.com/assets/6012231/17459933/473f7700-5c04-11e6-97c4-843692045c61.png)
![screen shot 2016-08-06 at 6 33 04 pm](https://cloud.githubusercontent.com/assets/6012231/17459934/4742560a-5c04-11e6-85de-45b227f405f4.png)
