### ISSUE TITLE
Implement CI

### ISSUE THREAD

**Issue by frankcash** [henryboldi/felony#72]
Probably best to use [TravisCI](https://travis-ci.com/)

Benefits
- Find build breaks earlier (Especially if through PR)
- Can package the app
- Nice for tests (in the future)

**Comment by MingweiSamuel** [comment]
Agree

**Comment by frankcash** [comment]
@henryboldi , can you register the repo on travis-ci.org

**Comment by frankcash** [comment]
Completely implemented as of now.

Need to implement testing now.
